### ISSUE TITLE
New to Puppet so what am I missing

### ISSUE THREAD

**Issue by HarryHarcourt** [hercules-team/augeasproviders_sysctl#11]
Hi Team
Sorry, I am new to Puppet, but I have installed the sysctl module to manage the /etc/sysctl.conf file but I see no "default" structure for the manifest and init.pp?
Also when I go into Puppet Enterprise I cannot bring up the class to add parameters?
Am I missing something?
Many thanks
Ben

**Comment by domcleal** [comment]
This module does not provide classes, it provides the `sysctl` resource type.

Create your own module/manifest and put `sysctl` resources inside your own classes, see the examples at https://github.com/hercules-team/augeasproviders_sysctl#documentation-and-examples.
