### ISSUE TITLE
Using with Hiera

### ISSUE THREAD

**Issue by mergar** [hercules-team/augeasproviders_sysctl#16]
You can write in the documentation/examples how we can use this provider to describe the sysctl parameters via hiera ? Thank you.

**Comment by raphink** [comment]
If you mean using data bindings, then you'll need a class to do the mapping. Something like:

```puppet
class profile::sysctl (
  $entries = {},
) {
  create_resources('sysctl', $entries)
}
```

and then store the sysctl entries in hiera as `profile::sysctl::entries`.

**Comment by tpdownes** [comment]
@mergar you might consider [tpdownes/sysctl](https://forge.puppet.com/tpdownes/sysctl) which was written to supports Puppet 4/5 with hiera v5.

**Comment by raphink** [comment]
This feature is also available in the `augeasproviders` module, where you can use the `augeasproviders::instances::sysctl_hash` hiera entry.
