### ISSUE TITLE
Error: Could not prefetch sysctl provider 'augeas': undefined method `context=' for #<Augeas:0x7f010c270830>

### ISSUE THREAD

**Issue by XMol** [hercules-team/augeasproviders_sysctl#32]
Hello,

we were looking to employ this Puppet custom resource type in order to manage our sysctl settings. However, on our Scientific Linux 6 (supposedly similar to RHEL 6) machines, the following error message is printed:

> Could not prefetch sysctl provider 'augeas': undefined method `context=' for #<Augeas:0x7f010c270830>

As far as we can tell, all requirements and dependencies are met:
* Puppet client and master are version 3.8.4
* Augeas v1.8.1
* augeasproviders_sysctl v2.2.1
* augeasproviders_core v2.4.0

I could not find 'context=' in the [augeas provider implementation](../blob/master/lib/puppet/provider/sysctl/augeas.rb), so I cannot tell where this error comes from. Did you by any chance encounter it in the past already?

Best regards,
Xavier.

**Comment by raphink** [comment]
How did you install the Augeas ruby bindings? Are you using the AIO Puppet packages or gems?

**Comment by XMol** [comment]
Hi Raphael.

> Are you using the AIO Puppet packages or gems?

To my knowledge, Puppet-3 has always been AIO distributed (starting with Puppet-4 some parts were segmented off) and we installed rpms, no gems. That includes ruby-augeas-bindings, that were installed due to dependencies of the puppet-3.8.1 rpm.

```
[root@sl6-node ~]# rpm -qR puppet | grep augeas
ruby-augeas

[root@sl6-node ~]# rpm -qi ruby-augeas
Name        : ruby-augeas                  Relocations: (not relocatable)
Version     : 0.4.1                             Vendor: (none)
Release     : 3.el6                         Build Date: Tue 18 Feb 2014 10:19:59 PM CET
Install Date: Tue 07 Aug 2018 01:27:11 PM CEST      Build Host: rpm-builder.delivery.puppetlabs.net
Group       : Development/Languages         Source RPM: ruby-augeas-0.4.1-3.el6.src.rpm
Size        : 45845                            License: LGPLv2+
Signature   : RSA/10, Tue 18 Feb 2014 10:23:40 PM CET, Key ID 1054b7a24bd6ec30
URL         : http://augeas.net
Summary     : Ruby bindings for Augeas
Description :
Ruby bindings for augeas.
```

Our standard repositories do not offer a newer version of this ruby-augeas rpm.

Best regards,
Xavier.

**Comment by raphink** [comment]
Is that an official ruby-augeas rpm?

There's two augeas gems, the official (https://rubygems.org/gems/ruby-augeas) and the fork (https://rubygems.org/gems/augeas). I'm wondering now what is the status with that now, as I don't see any releases in the latter for 0.6.0… @lutter do you remember?

**Comment by XMol** [comment]
> Is that an official ruby-augeas rpm?

Can it get more official than an rpm build by puppetlabs? 😕 Would it be fine to install the gems additionally to this rpm? If not, we have a dependency problem at hand.

**Comment by raphink** [comment]
AIO packages (`puppet-agent`) don't require `ruby-augeas` packages. I didn't even know Puppetlabs had Augeas packages, and these shouldn't be necessary.

**Comment by XMol** [comment]
Admittedly, our Puppet version is quite outdated. We have not installed a `puppet-agent` rpm, because that doesn't exist for Puppet version 3. `puppet-agent-1.0.0` is released first for Puppet-4.

As shown before, `puppet-3.8.4-1.el6.noarch` requires the `ruby-augeas` feature, which is satisfied by `ruby-augeas-0.4.1-3.el6.x86_64`, both provided by puppetlabs ([puppet](https://yum.puppetlabs.com/el/6/products/x86_64/) and [ruby-augeas](https://yum.puppetlabs.com/el/6Server/dependencies/x86_64/)).

**Comment by raphink** [comment]
It's very surprising you don't get 0.5.0 though, as it was released in 2013, and is required for quite a few augeasproviders features.

**Comment by XMol** [comment]
0.4.1 is the only rpm provided by the above linked yum repository hosted by puppetlabs. So I'm not that surprised. 🙂

**Comment by raphink** [comment]
As a note, Puppet 3 has been EOL for almost 3 years, and even Puppet 4 was retired about a year ago, so this module won't be adapted to work with Puppet 3.

**Comment by XMol** [comment]
Yes, that is what I had exepcted. Thank you for your time anyway.
