### ISSUE TITLE
Verifying hex or integer sysctl values causes augeas error

### ISSUE THREAD

**Issue by tuxmea** [hercules-team/augeasproviders_sysctl#34]
Setting a hex value within sysctl works fine:
```
profile::base::sysctl::rules:
  'kernel.shmmax':
    ensure: present
    value: '0xffffffffffffffff'
    target: '/etc/sysctl.d/90_rules.conf'
    comment: 'Increase defaults for IPC'
```

But on second run, error show up:
```
Notice: Sysctl[kernel.shmmax]/value changed live value from '18446744073709551615' to '0xffffffffffffffff'
Error: Sysctl[kernel.shmmax]: Could not evaluate: Failed to save Augeas tree to file. See debug log for details.
```

Running in debug mode shows the following:
```
Debug: Executing: '/sbin/sysctl -w kernel.shmmax=0xffffffffffffffff'
Debug: Puppet::Type::Sysctl::ProviderAugeas: Save failure details:
/augeas/files/etc/sysctl.d/90_rules.conf/error/path = /files/etc/sysctl.d/90_rules.conf/files/etc/sysctl.d/90_rules.conf/kernel.shmmax[1]
/augeas/files/etc/sysctl.d/90_rules.conf/error/lens = /opt/puppetlabs/puppet/share/augeas/lenses/dist/simplevars.aug:35.14.-40:
/augeas/files/etc/sysctl.d/90_rules.conf/error/message = None of the alternatives in the union match
```
Similar error shows up when reading integer 0 values:
```
Debug: Executing: '/sbin/sysctl -n net.ipv4.ip_forward'
```
Running command on command line returns Integer number 0
But sysctl type/provider reads value as empty string.

**Comment by tuxmea** [comment]
@SimonHoenscheid : FYI

**Comment by raphink** [comment]
Which version of Augeas are you running?

**Comment by SimonHoenscheid** [comment]
Puppet version 6.4.2, Augeas version 1.11.0

**Comment by raphink** [comment]
Are you able to show me the content in your `90_rules.conf` file, or maybe just test with another target file?

**Comment by SimonHoenscheid** [comment]
Showing the file is not possible, because it is a closed evironment, nothing in, nothing out.  But I can check with an other file.

**Comment by SimonHoenscheid** [comment]
The result with an other file is the same

**Comment by tuxmea** [comment]
@SimonHoenscheid just paste the lines with ipv4forward and where we set the hex value here.

**Comment by raphink** [comment]
@SimonHoenscheid you mean you tested with an empty target and it did the same thing, right?

**Comment by SimonHoenscheid** [comment]
@raphink yes

**Comment by tuxmea** [comment]
content of file:
```
cat /tmp/shmmax.conf 
kernel.shmmax = 0xffffffffffffffff
```
