### ISSUE TITLE
discrepancy between title and name

### ISSUE THREAD

**Issue by igalic** [hercules-team/augeasproviders_sysctl#37]
This code doesn't work

```puppet
sysctl { "4 - Refresh Route config":
  name    => 'net.ipv4.route.flush',
  value   => 1,
  persist => false,
}
```

"and throws the error: Could not evaluate: `net.ipv4.route.flush` is not a valid sysctl key"

This code works:

```puppet
sysctl { "'net.ipv4.route.flush",
  value   => 1,
  persist => false,
}
```

The reason might stem from `net.ipv4.route.flush` not showing up in `sysctl --all` (self.instances)

I realize this is a very special case, that might be better served with an `exec`, especially since we want a refresh-only here! But i'm submitting it non-the-less as someone might stumble of a similar issue.

**Comment by raphink** [comment]
Hey @igalic! I'm guessing there's a typo in the working code, where there's an extra `'` in the title, correct?

**Comment by igalic** [comment]
maaaaaaaaaaybe 🙇‍♀
