### ISSUE TITLE
Works on OpenBSD!

### ISSUE THREAD

**Issue by bjer** [hercules-team/augeasproviders_sysctl#5]
Seems to work on OpenBSD, tried it on 5.7 and 5.8; /etc/sysctl.conf is updated and sysctl values are updated without the need of a reboot. I think it's safe to add OpenBSD to the compatible os list. Probably should work on FreeBSD as well but I have not tested yet.

**Comment by raphink** [comment]
Great! Could you provide a pr for this please?

**Comment by olevole** [comment]
See https://github.com/hercules-team/augeasproviders_sysctl/pull/10
