### ISSUE TITLE
The sysctl type should have a :silent option

### ISSUE THREAD

**Issue by trevor-vaughan** [hercules-team/augeasproviders_sysctl#6]
In some cases (NFS in particular), the sysctl value is not present until after kernel modules have been loaded by the service starting.

In this case, the user should have the option to tell the sysctl provider to not worry about the value if it fails to apply.

My suggestion is the following:

Change `def live_value` to the following (untested):

```ruby
def live_value
  if resource[:silent] == :true
    debug('augeasproviders_sysctl not setting live value on user request')
    return resource[:value]
  else
    return self.class.sysctl_get(resource[:name])
  end
end
```

**Comment by raphink** [comment]
OK. It would be good to have a test with it making no changes are applied to the file.

**Comment by trevor-vaughan** [comment]
Yep. I'll probably be working on this in the near future and will, as usual, drag in acceptance tests to check modifications on a live system.

**Comment by raphink** [comment]
Good :smile:

**Comment by trevor-vaughan** [comment]
@raphink This is ready for review if you get a chance. Should take about 5 minutes.

**Comment by raphink** [comment]
@trevor-vaughan Sorry I was on vacation last week. I see you went ahead.

**Comment by trevor-vaughan** [comment]
@raphink Yeah, I was starting to diverge too much upstream and had ended up testing it on several other systems. If you find issues, I'll patch it.

**Comment by raphink** [comment]
No problem. Please make a minor release for that.
