### ISSUE TITLE
Release 2.6.2 missing on Forge

### ISSUE THREAD

**Issue by treydock** [hercules-team/augeasproviders_sysctl#64]
I see commits to CHANGELOG.md and metadata.json for 2.6.2 but I don't see a tag or a release to forge.  Wasn't sure if maybe a release step got missed or something or if the process is on-going?

**Comment by trevor-vaughan** [comment]
Unfortunately, I don't have that power so I'll have to defer to someone that does

**Comment by treydock** [comment]
This release is now available on forge, closing issue.
